// Hyprland bridge — HyprDesk keeps its own hyprdesk.conf / hyprdesk.lua, generated whole from its saved state.
// Puente con Hyprland — HyprDesk mantiene su propio hyprdesk.conf / hyprdesk.lua, generado entero desde su estado guardado.

use crate::config::{config_dir, hypr_dir};
use serde::{Deserialize, Serialize};
use std::fs;
use std::io;
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};

pub const LAYOUT_VERSION: u32 = 2;
const HOOK_MARK: &str = "HyprDesk — keep this last / déjalo al final";
const HEADER: &str = "Generated by HyprDesk, edits are overwritten / Generado por HyprDesk, los cambios se sobrescriben";

// ── Provider / Formato ───────────────────────────────────────

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Provider {
    Hyprlang,
    Lua,
}

impl Provider {
    pub fn managed_name(self) -> &'static str {
        match self {
            Provider::Hyprlang => "hyprdesk.conf",
            Provider::Lua => "hyprdesk.lua",
        }
    }

    pub fn entry_name(self) -> &'static str {
        match self {
            Provider::Hyprlang => "hyprland.conf",
            Provider::Lua => "hyprland.lua",
        }
    }

    fn comment(self) -> &'static str {
        match self {
            Provider::Hyprlang => "#",
            Provider::Lua => "--",
        }
    }
}

// The running compositor knows which parser it loaded; the files are only a fallback / El compositor en marcha sabe qué parser cargó; los ficheros son solo un respaldo
pub fn provider() -> Provider {
    let running = Command::new("hyprctl")
        .args(["status", "-j"])
        .output()
        .ok()
        .and_then(|o| serde_json::from_slice::<serde_json::Value>(&o.stdout).ok())
        .and_then(|v| v["configProvider"].as_str().map(str::to_string));
    match running.as_deref() {
        Some("lua") => Provider::Lua,
        Some("hyprlang") => Provider::Hyprlang,
        _ if hypr_dir().join("hyprland.lua").exists() => Provider::Lua,
        _ => Provider::Hyprlang,
    }
}

// ── State / Estado ───────────────────────────────────────────

#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
pub struct MonitorRule {
    pub name: String,
    pub mode: String,
    pub x: i32,
    pub y: i32,
    pub scale: f64,
    pub transform: u32,
}

#[derive(Serialize, Deserialize, Clone, Debug, PartialEq)]
pub struct AppOpacity {
    pub app: String,
    pub active: f64,
}

// None or empty leaves that setting to the user's own config / None o vacío deja ese ajuste a la config del usuario
#[derive(Serialize, Deserialize, Clone, Debug, Default, PartialEq)]
#[serde(default)]
pub struct HyprState {
    pub monitors: Vec<MonitorRule>,
    pub primary: Option<String>,
    pub opacity_active: Option<f64>,
    pub opacity_inactive: Option<f64>,
    pub app_opacity: Vec<AppOpacity>,
    pub autostart: Option<String>,
    pub layout_version: u32,
}

impl HyprState {
    pub fn set_monitor(&mut self, rule: MonitorRule) {
        match self.monitors.iter_mut().find(|m| m.name == rule.name) {
            Some(m) => *m = rule,
            None => self.monitors.push(rule),
        }
    }

    pub fn set_app_opacity(&mut self, app: &str, active: f64) {
        match self.app_opacity.iter_mut().find(|a| a.app == app) {
            Some(a) => a.active = active,
            None => self.app_opacity.push(AppOpacity { app: app.to_string(), active }),
        }
    }
}

fn state_path(dir: &Path) -> PathBuf {
    dir.join("hypr.json")
}

pub fn load_state_in(dir: &Path) -> HyprState {
    fs::read_to_string(state_path(dir))
        .ok()
        .and_then(|s| serde_json::from_str(&s).ok())
        .unwrap_or_default()
}

pub fn save_state_in(dir: &Path, state: &HyprState) -> io::Result<()> {
    fs::create_dir_all(dir)?;
    let json = serde_json::to_string_pretty(state).map_err(io::Error::other)?;
    write_atomic(&state_path(dir), &json)
}

pub fn load_state() -> HyprState {
    load_state_in(&config_dir())
}

// ── Rendering / Generación ───────────────────────────────────

fn fmt_f(v: f64) -> String {
    format!("{v:.2}")
}

pub fn lua_str(s: &str) -> String {
    let mut out = String::with_capacity(s.len() + 2);
    out.push('"');
    for c in s.chars() {
        match c {
            '\\' => out.push_str("\\\\"),
            '"' => out.push_str("\\\""),
            '\n' => out.push_str("\\n"),
            '\r' => out.push_str("\\r"),
            _ => out.push(c),
        }
    }
    out.push('"');
    out
}

// hyprctl prints 1920x1080@60.00Hz, the config takes it without the Hz / hyprctl imprime 1920x1080@60.00Hz, la config lo acepta sin el Hz
fn bare_mode(mode: &str) -> &str {
    let mode = mode.trim();
    mode.strip_suffix("Hz").unwrap_or(mode)
}

pub fn monitor_line(p: Provider, m: &MonitorRule) -> String {
    match p {
        Provider::Hyprlang => format!(
            "monitor = {},{},{}x{},{},transform,{}",
            m.name, bare_mode(&m.mode), m.x, m.y, fmt_f(m.scale), m.transform
        ),
        Provider::Lua => format!(
            "hl.monitor({{ output = {}, mode = {}, position = {}, scale = {}, transform = {} }})",
            lua_str(&m.name),
            lua_str(bare_mode(&m.mode)),
            lua_str(&format!("{}x{}", m.x, m.y)),
            fmt_f(m.scale),
            m.transform
        ),
    }
}

pub fn primary_line(p: Provider, name: &str) -> String {
    match p {
        Provider::Hyprlang => format!("workspace = 1, monitor:{name}, default:true"),
        Provider::Lua => format!(
            "hl.workspace_rule({{ workspace = \"1\", monitor = {}, default = true }})",
            lua_str(name)
        ),
    }
}

pub fn opacity_lines(p: Provider, state: &HyprState) -> Vec<String> {
    let set: Vec<(&str, f64)> = [
        ("active_opacity", state.opacity_active),
        ("inactive_opacity", state.opacity_inactive),
    ]
    .into_iter()
    .filter_map(|(key, v)| v.map(|v| (key, v)))
    .collect();
    if set.is_empty() {
        return Vec::new();
    }
    match p {
        Provider::Hyprlang => set
            .iter()
            .map(|(key, v)| format!("decoration:{key} = {}", fmt_f(*v)))
            .collect(),
        Provider::Lua => {
            let fields: Vec<String> = set.iter().map(|(key, v)| format!("{key} = {}", fmt_f(*v))).collect();
            vec![format!("hl.config({{ decoration = {{ {} }} }})", fields.join(", "))]
        }
    }
}

fn app_rule_line(p: Provider, a: &AppOpacity) -> String {
    match p {
        Provider::Hyprlang => format!("windowrule = match:class ^({})$, opacity {}", a.app, fmt_f(a.active)),
        // A named rule replaces the one with the same name, so re-applying never stacks / Una regla con nombre sustituye a la del mismo nombre, así que reaplicar nunca acumula
        Provider::Lua => format!(
            "hl.window_rule({{ name = {}, match = {{ class = {} }}, opacity = {} }})",
            lua_str(&format!("hyprdesk-opacity-{}", a.app)),
            lua_str(&format!("^({})$", a.app)),
            lua_str(&fmt_f(a.active))
        ),
    }
}

fn autostart_line(p: Provider, script: &str) -> String {
    match p {
        Provider::Hyprlang => format!("exec-once = {script}"),
        Provider::Lua => format!(
            "hl.on(\"hyprland.start\", function() hl.exec_cmd({}) end)",
            lua_str(script)
        ),
    }
}

// Window classes end up inside a rule, so anything that could break its syntax is refused / Las clases de ventana acaban dentro de una regla, así que se rechaza lo que pueda romper su sintaxis
pub fn valid_class(app: &str) -> bool {
    !app.trim().is_empty() && !app.chars().any(|c| c.is_control() || matches!(c, ',' | '(' | ')' | '"' | '\\'))
}

pub fn render(p: Provider, state: &HyprState) -> String {
    let c = p.comment();
    let mut out = format!("{c} {HEADER}\n");
    let mut section = |title: &str, lines: Vec<String>| {
        if lines.is_empty() {
            return;
        }
        out.push_str(&format!("\n{c} {title}\n"));
        for line in lines {
            out.push_str(&line);
            out.push('\n');
        }
    };
    section("Monitors / Monitores", state.monitors.iter().map(|m| monitor_line(p, m)).collect());
    section("Primary monitor / Monitor principal", state.primary.iter().map(|n| primary_line(p, n)).collect());
    section(
        "Opacity / Opacidad",
        opacity_lines(p, state)
            .into_iter()
            .chain(state.app_opacity.iter().map(|a| app_rule_line(p, a)))
            .collect(),
    );
    section("Autostart / Inicio automático", state.autostart.iter().map(|s| autostart_line(p, s)).collect());
    out
}

// ── Files / Ficheros ─────────────────────────────────────────

// Writes beside the real file and renames over it, following symlinks so dotfile setups keep their links / Escribe junto al fichero real y lo renombra encima, siguiendo symlinks para que los dotfiles conserven sus enlaces
pub fn write_atomic(path: &Path, content: &str) -> io::Result<()> {
    let target = fs::canonicalize(path).unwrap_or_else(|_| path.to_path_buf());
    let name = target.file_name().and_then(|n| n.to_str()).unwrap_or("file");
    let tmp = target.with_file_name(format!(".{name}.hyprdesk-tmp"));
    fs::write(&tmp, content)?;
    fs::rename(&tmp, &target)
}

fn hook_block(p: Provider, hypr: &Path) -> String {
    match p {
        Provider::Hyprlang => format!("# {HOOK_MARK}\nsource = {}\n", hypr.join(p.managed_name()).display()),
        Provider::Lua => format!("-- {HOOK_MARK}\npcall(require, \"hyprdesk\")\n"),
    }
}

pub fn has_hook(p: Provider, content: &str) -> bool {
    content
        .lines()
        .map(str::trim)
        .filter(|l| !l.starts_with(p.comment()))
        .any(|l| match p {
            Provider::Hyprlang => l.starts_with("source") && l.contains(p.managed_name()),
            Provider::Lua => l.contains("require") && (l.contains("\"hyprdesk\"") || l.contains("'hyprdesk'")),
        })
}

// Appends the include once, at the very end so HyprDesk's values win / Añade el include una sola vez, al final del todo para que ganen los valores de HyprDesk
pub fn ensure_hook(p: Provider, hypr: &Path) -> io::Result<()> {
    let entry = hypr.join(p.entry_name());
    let content = match fs::read_to_string(&entry) {
        Ok(c) => c,
        Err(e) if e.kind() == io::ErrorKind::NotFound => return Ok(()),
        Err(e) => return Err(e),
    };
    if has_hook(p, &content) {
        return Ok(());
    }
    write_atomic(&entry, &format!("{}\n\n{}", content.trim_end(), hook_block(p, hypr)))
}

// ── Compositor / Compositor ──────────────────────────────────

pub trait Compositor {
    // Applies lines to the running session; Err carries Hyprland's own message / Aplica líneas a la sesión en marcha; Err lleva el mensaje de Hyprland
    fn apply(&self, p: Provider, lines: &[String]) -> Result<(), String>;
    fn reload(&self, monitors: bool);
    fn errors(&self) -> Vec<String>;
}

pub struct Hyprctl;

fn hyprctl_text(args: &[&str]) -> Result<String, String> {
    let out = Command::new("hyprctl").args(args).output().map_err(|e| e.to_string())?;
    Ok(String::from_utf8_lossy(&out.stdout).trim().to_string())
}

impl Compositor for Hyprctl {
    fn apply(&self, p: Provider, lines: &[String]) -> Result<(), String> {
        for line in lines {
            // Both answer "ok" and exit 0 even on failure, so the text is what counts / Los dos responden "ok" y salen con 0 incluso al fallar, así que cuenta el texto
            let reply = match p {
                Provider::Lua => hyprctl_text(&["eval", line])?,
                Provider::Hyprlang => {
                    let (key, value) = line.split_once('=').ok_or_else(|| line.clone())?;
                    hyprctl_text(&["keyword", key.trim(), value.trim()])?
                }
            };
            if reply != "ok" {
                return Err(reply);
            }
        }
        Ok(())
    }

    fn reload(&self, monitors: bool) {
        let args: &[&str] = if monitors { &["reload"] } else { &["reload", "config-only"] };
        let _ = Command::new("hyprctl").args(args).stdout(Stdio::null()).stderr(Stdio::null()).status();
    }

    fn errors(&self) -> Vec<String> {
        hyprctl_text(&["configerrors", "-j"])
            .ok()
            .and_then(|s| serde_json::from_str::<Vec<String>>(&s).ok())
            .unwrap_or_default()
            .into_iter()
            .filter(|e| !e.trim().is_empty())
            .collect()
    }
}

// ── Commit / Confirmar ───────────────────────────────────────

// Live first, then the file, then Hyprland's verdict; errors in our file put the previous one back / Primero en vivo, luego el fichero, luego el veredicto de Hyprland; si nuestro fichero da errores se restaura el anterior
pub fn commit_in(
    hypr: &Path,
    state_dir: &Path,
    p: Provider,
    next: &HyprState,
    live: &[String],
    reload_monitors: bool,
    hc: &dyn Compositor,
) -> Result<(), String> {
    hc.apply(p, live)?;

    let managed = hypr.join(p.managed_name());
    let previous = load_state_in(state_dir);
    fs::create_dir_all(hypr).map_err(|e| e.to_string())?;
    // The file exists before the hook points at it, a missing module is an error in Lua / El fichero existe antes de que el enganche lo apunte, un módulo ausente es un error en Lua
    write_atomic(&managed, &render(p, next)).map_err(|e| e.to_string())?;
    ensure_hook(p, hypr).map_err(|e| e.to_string())?;
    save_state_in(state_dir, next).map_err(|e| e.to_string())?;
    // hyprlang already took monitors live through keyword, only Lua needs them from the file / hyprlang ya recibió los monitores en vivo por keyword, solo Lua los necesita del fichero
    let full = reload_monitors && p == Provider::Lua;
    hc.reload(full);

    let ours: Vec<String> = hc.errors().into_iter().filter(|e| e.contains(p.managed_name())).collect();
    if ours.is_empty() {
        return Ok(());
    }
    let _ = write_atomic(&managed, &render(p, &previous));
    let _ = save_state_in(state_dir, &previous);
    hc.reload(full);
    Err(ours.join("\n"))
}

// Edits the saved state and pushes it to Hyprland / Edita el estado guardado y lo lleva a Hyprland
pub fn update(
    edit: impl FnOnce(&mut HyprState),
    live: impl FnOnce(Provider, &HyprState) -> Vec<String>,
    reload_monitors: bool,
) -> Result<(), String> {
    let p = provider();
    let mut next = load_state();
    edit(&mut next);
    let lines = live(p, &next);
    commit_in(&hypr_dir(), &config_dir(), p, &next, &lines, reload_monitors, &Hyprctl)
}

// ── Runtime reads / Lecturas en vivo ─────────────────────────

pub fn get_float_option(name: &str) -> Option<f64> {
    let text = hyprctl_text(&["getoption", name, "-j"]).ok()?;
    serde_json::from_str::<serde_json::Value>(&text).ok()?["float"].as_f64()
}

pub fn workspace_one_monitor() -> Option<String> {
    let text = hyprctl_text(&["workspacerules", "-j"]).ok()?;
    let rules: Vec<serde_json::Value> = serde_json::from_str(&text).ok()?;
    rules
        .iter()
        .rev()
        .find(|r| r["workspaceString"].as_str() == Some("1"))
        .and_then(|r| r["monitor"].as_str())
        .map(str::to_string)
}

// ── Conflicts / Conflictos ───────────────────────────────────

// Settings HyprDesk wrote that the running session shows differently, i.e. the user's config overrides them later / Ajustes que HyprDesk escribió y que la sesión muestra distintos, es decir, la config del usuario los pisa después
#[derive(Clone, Debug, Default, PartialEq)]
pub struct Conflicts {
    pub opacity_active: bool,
    pub opacity_inactive: bool,
    pub primary: bool,
}

fn differs(expected: Option<f64>, actual: Option<f64>) -> bool {
    matches!((expected, actual), (Some(e), Some(a)) if (e - a).abs() > 0.006)
}

pub fn conflicts_between(state: &HyprState, active: Option<f64>, inactive: Option<f64>, primary: Option<&str>) -> Conflicts {
    Conflicts {
        opacity_active: differs(state.opacity_active, active),
        opacity_inactive: differs(state.opacity_inactive, inactive),
        primary: matches!((&state.primary, primary), (Some(e), Some(a)) if e != a),
    }
}

pub fn conflicts() -> Conflicts {
    let primary = workspace_one_monitor();
    conflicts_between(
        &load_state(),
        get_float_option("decoration:active_opacity"),
        get_float_option("decoration:inactive_opacity"),
        primary.as_deref(),
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::cell::RefCell;

    fn scratch(name: &str) -> PathBuf {
        let dir = std::env::temp_dir().join(format!("hyprdesk-{name}-{}", std::process::id()));
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(dir.join(".config/hypr")).unwrap();
        dir
    }

    fn sample() -> HyprState {
        HyprState {
            monitors: vec![MonitorRule {
                name: "HDMI-A-1".into(),
                mode: "1920x1080@60.00Hz".into(),
                x: -1920,
                y: 0,
                scale: 1.0,
                transform: 3,
            }],
            primary: Some("HDMI-A-2".into()),
            opacity_active: Some(0.95),
            opacity_inactive: None,
            app_opacity: vec![AppOpacity { app: "org.gnome.Nautilus".into(), active: 0.9 }],
            autostart: Some("/home/u/.config/hypr/hyprdesk-startup.sh".into()),
            layout_version: LAYOUT_VERSION,
        }
    }

    // Stands in for hyprctl so tests never touch the real session / Sustituye a hyprctl para que los tests nunca toquen la sesión real
    #[derive(Default)]
    struct FakeHyprland {
        applied: RefCell<Vec<String>>,
        reloads: RefCell<u32>,
        reject: Option<String>,
        errors: Vec<String>,
    }

    impl Compositor for FakeHyprland {
        fn apply(&self, _: Provider, lines: &[String]) -> Result<(), String> {
            if let Some(msg) = &self.reject {
                return Err(msg.clone());
            }
            self.applied.borrow_mut().extend(lines.iter().cloned());
            Ok(())
        }
        fn reload(&self, _: bool) {
            *self.reloads.borrow_mut() += 1;
        }
        fn errors(&self) -> Vec<String> {
            self.errors.clone()
        }
    }

    #[test]
    fn conf_file_is_rendered_in_hyprlang() {
        assert_eq!(
            render(Provider::Hyprlang, &sample()),
            "# Generated by HyprDesk, edits are overwritten / Generado por HyprDesk, los cambios se sobrescriben\n\
             \n# Monitors / Monitores\n\
             monitor = HDMI-A-1,1920x1080@60.00,-1920x0,1.00,transform,3\n\
             \n# Primary monitor / Monitor principal\n\
             workspace = 1, monitor:HDMI-A-2, default:true\n\
             \n# Opacity / Opacidad\n\
             decoration:active_opacity = 0.95\n\
             windowrule = match:class ^(org.gnome.Nautilus)$, opacity 0.90\n\
             \n# Autostart / Inicio automático\n\
             exec-once = /home/u/.config/hypr/hyprdesk-startup.sh\n"
        );
    }

    #[test]
    fn lua_file_uses_the_real_hl_api() {
        assert_eq!(
            render(Provider::Lua, &sample()),
            "-- Generated by HyprDesk, edits are overwritten / Generado por HyprDesk, los cambios se sobrescriben\n\
             \n-- Monitors / Monitores\n\
             hl.monitor({ output = \"HDMI-A-1\", mode = \"1920x1080@60.00\", position = \"-1920x0\", scale = 1.00, transform = 3 })\n\
             \n-- Primary monitor / Monitor principal\n\
             hl.workspace_rule({ workspace = \"1\", monitor = \"HDMI-A-2\", default = true })\n\
             \n-- Opacity / Opacidad\n\
             hl.config({ decoration = { active_opacity = 0.95 } })\n\
             hl.window_rule({ name = \"hyprdesk-opacity-org.gnome.Nautilus\", match = { class = \"^(org.gnome.Nautilus)$\" }, opacity = \"0.90\" })\n\
             \n-- Autostart / Inicio automático\n\
             hl.on(\"hyprland.start\", function() hl.exec_cmd(\"/home/u/.config/hypr/hyprdesk-startup.sh\") end)\n"
        );
        assert!(!render(Provider::Lua, &sample()).contains("hl.keyword"));
    }

    #[test]
    fn untouched_settings_stay_out_of_the_file() {
        let empty = HyprState::default();
        assert_eq!(render(Provider::Hyprlang, &empty).lines().count(), 1);
        assert_eq!(render(Provider::Lua, &empty).lines().count(), 1);
        let one = HyprState { opacity_inactive: Some(0.8), ..HyprState::default() };
        assert_eq!(opacity_lines(Provider::Hyprlang, &one), ["decoration:inactive_opacity = 0.80"]);
        assert_eq!(opacity_lines(Provider::Lua, &one), ["hl.config({ decoration = { inactive_opacity = 0.80 } })"]);
    }

    #[test]
    fn lua_strings_cannot_escape_their_quotes() {
        assert_eq!(lua_str(r#"a"b\c"#), r#""a\"b\\c""#);
        assert_eq!(lua_str("a\nb"), r#""a\nb""#);
        assert!(!valid_class("kitty, opacity 0.1"));
        assert!(!valid_class("a)b"));
        assert!(!valid_class("  "));
        assert!(valid_class("org.gnome.Nautilus"));
    }

    #[test]
    fn hook_is_added_once_and_comments_do_not_count() {
        for p in [Provider::Hyprlang, Provider::Lua] {
            let home = scratch(&format!("hook-{p:?}"));
            let hypr = home.join(".config/hypr");
            let entry = hypr.join(p.entry_name());
            let commented = format!("{} source = {}\n{} pcall(require, \"hyprdesk\")\n", p.comment(), hypr.join("hyprdesk.conf").display(), p.comment());
            fs::write(&entry, format!("user line\n{commented}")).unwrap();

            ensure_hook(p, &hypr).unwrap();
            ensure_hook(p, &hypr).unwrap();

            let text = fs::read_to_string(&entry).unwrap();
            assert!(text.starts_with("user line\n"), "{text}");
            assert_eq!(text.matches(HOOK_MARK).count(), 1, "{text}");
            assert!(text.trim_end().ends_with(hook_block(p, &hypr).trim_end()), "{text}");
        }
    }

    #[test]
    fn a_missing_entry_file_is_not_created() {
        let home = scratch("no-entry");
        let hypr = home.join(".config/hypr");
        ensure_hook(Provider::Lua, &hypr).unwrap();
        assert!(!hypr.join("hyprland.lua").exists());
    }

    #[test]
    fn commit_writes_file_hook_and_state() {
        let home = scratch("commit");
        let hypr = home.join(".config/hypr");
        let state_dir = home.join(".config/hyprdesk");
        fs::write(hypr.join("hyprland.conf"), "monitor = , preferred, auto, 1\n").unwrap();
        let hc = FakeHyprland::default();
        let live = vec![primary_line(Provider::Hyprlang, "HDMI-A-2")];

        commit_in(&hypr, &state_dir, Provider::Hyprlang, &sample(), &live, false, &hc).unwrap();
        commit_in(&hypr, &state_dir, Provider::Hyprlang, &sample(), &live, false, &hc).unwrap();

        assert_eq!(fs::read_to_string(hypr.join("hyprdesk.conf")).unwrap(), render(Provider::Hyprlang, &sample()));
        let entry = fs::read_to_string(hypr.join("hyprland.conf")).unwrap();
        assert!(entry.starts_with("monitor = , preferred, auto, 1\n"));
        assert_eq!(entry.matches("hyprdesk.conf").count(), 1, "{entry}");
        assert_eq!(load_state_in(&state_dir), sample());
        assert_eq!(hc.applied.borrow().len(), 2);
        assert_eq!(*hc.reloads.borrow(), 2);
    }

    #[test]
    fn a_change_hyprland_rejects_live_is_never_saved() {
        let home = scratch("reject");
        let hypr = home.join(".config/hypr");
        let state_dir = home.join(".config/hyprdesk");
        let hc = FakeHyprland { reject: Some("error: attempt to call a nil value".into()), ..Default::default() };

        let err = commit_in(&hypr, &state_dir, Provider::Lua, &sample(), &["x".into()], false, &hc).unwrap_err();

        assert!(err.contains("nil value"));
        assert!(!hypr.join("hyprdesk.lua").exists());
        assert_eq!(load_state_in(&state_dir), HyprState::default());
    }

    #[test]
    fn errors_in_our_file_roll_back_to_the_previous_one() {
        let home = scratch("rollback");
        let hypr = home.join(".config/hypr");
        let state_dir = home.join(".config/hyprdesk");
        let good = HyprState { opacity_active: Some(0.9), ..HyprState::default() };
        commit_in(&hypr, &state_dir, Provider::Lua, &good, &[], false, &FakeHyprland::default()).unwrap();

        let broken = FakeHyprland {
            errors: vec![format!("require(\"hyprdesk\"): {}:3: boom", hypr.join("hyprdesk.lua").display())],
            ..Default::default()
        };
        let err = commit_in(&hypr, &state_dir, Provider::Lua, &sample(), &[], true, &broken).unwrap_err();

        assert!(err.contains("boom"));
        assert_eq!(fs::read_to_string(hypr.join("hyprdesk.lua")).unwrap(), render(Provider::Lua, &good));
        assert_eq!(load_state_in(&state_dir), good);
        assert_eq!(*broken.reloads.borrow(), 2);
    }

    #[test]
    fn errors_in_the_users_files_are_not_ours_to_undo() {
        let home = scratch("foreign-errors");
        let hypr = home.join(".config/hypr");
        let state_dir = home.join(".config/hyprdesk");
        let hc = FakeHyprland {
            errors: vec!["Config error in file /home/u/.config/hypr/UserKeybinds.conf at line 4".into()],
            ..Default::default()
        };
        commit_in(&hypr, &state_dir, Provider::Hyprlang, &sample(), &[], false, &hc).unwrap();
        assert_eq!(load_state_in(&state_dir), sample());
    }

    #[test]
    fn a_symlinked_entry_keeps_its_link() {
        let home = scratch("symlink");
        let hypr = home.join(".config/hypr");
        let real = home.join("dotfiles-hyprland.conf");
        fs::write(&real, "exec-once = waybar\n").unwrap();
        std::os::unix::fs::symlink(&real, hypr.join("hyprland.conf")).unwrap();

        ensure_hook(Provider::Hyprlang, &hypr).unwrap();

        assert!(fs::symlink_metadata(hypr.join("hyprland.conf")).unwrap().file_type().is_symlink());
        assert!(fs::read_to_string(&real).unwrap().contains("hyprdesk.conf"));
    }

    #[test]
    fn conflicts_show_only_where_the_session_disagrees() {
        let state = sample();
        assert_eq!(conflicts_between(&state, Some(0.95), Some(0.5), Some("HDMI-A-2")), Conflicts::default());
        let c = conflicts_between(&state, Some(0.80), None, Some("DP-1"));
        assert!(c.opacity_active && c.primary && !c.opacity_inactive);
    }

    // Asks the installed Hyprland itself to parse what we generate; skipped where it is not installed / Pide al propio Hyprland instalado que interprete lo generado; se omite donde no está instalado
    #[test]
    fn hyprland_accepts_both_generated_files() {
        if Command::new("Hyprland").arg("--version").output().is_err() {
            return;
        }
        for p in [Provider::Hyprlang, Provider::Lua] {
            let home = scratch(&format!("verify-{p:?}"));
            let hypr = home.join(".config/hypr");
            fs::write(hypr.join(p.entry_name()), "").unwrap();
            commit_in(&hypr, &home.join(".config/hyprdesk"), p, &sample(), &[], false, &FakeHyprland::default()).unwrap();

            let out = Command::new("Hyprland")
                .args(["--verify-config", "--config"])
                .arg(hypr.join(p.entry_name()))
                .env("HOME", &home)
                .env("XDG_CONFIG_HOME", home.join(".config"))
                .output()
                .unwrap();
            let text = String::from_utf8_lossy(&out.stdout);
            assert!(text.contains("config ok"), "{p:?}:\n{text}");
        }
    }
}
